#!/bin/bash
clear
figlet "Shout Log"
cd ~/Projects/ShoutLog/
git pull
firefox klat.com/klatchat.php klat.com/klatchat.php klat.com/klatchat.php klat.com/klatchat.php klat.com/klatchat.php klat.com/klatchat.php klat.com/klatchat.php klat.com/klatchat.php klat.com/klatchat.php &
python3 ShoutWall3.py
git add .
git commit -m "updating shout log files"
git push
